# Generated by Django 5.2.12 on 2026-03-13 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=120)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Awaiting Payment'), ('processing', 'Processing Request'), ('document_preparation', 'Document Preparation'), ('ready_for_release', 'Ready For Release'), ('completed', 'Completed'), ('incomplete', 'Incomplete Requirements'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('release_mode', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='digital', max_length=10)),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_required', max_length=20)),
                ('or_number', models.CharField(blank=True, max_length=50)),
                ('tracking_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
