# Generated by Django 6.0.3 on 2026-03-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='semester_and_academic_year',
            field=models.CharField(blank=True, help_text='e.g., 1st Semester 2023-2024', max_length=50),
        ),
    ]
