# Generated by Django 6.0.3 on 2026-05-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_semester_and_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='number_of_copies',
            field=models.IntegerField(default=1, help_text='Number of copies needed'),
        ),
    ]
